import { Poppins } from "next/font/google";
import "./globals.css";

const geistSans = Poppins({
  subsets: ["latin"],
  weight: ["100", "300", "500", "700", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.className}  h-full antialiased`}>
      <body
        className="min-h-full flex flex-col
       
       "
      >
        {children}
      </body>
    </html>
  );
}
